name: Run Ruby script

on: [push]

jobs:
  run-ruby-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1 # Specify the Ruby version you want to use

      - name: Install dependencies
        run: bundle install

      - name: Run Ruby script
        run: |
          ruby -v # Check Ruby version
          ruby script.rb # Replace 'script.rb' with your Ruby script
