name: Run Ruby script
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push]

jobs:
  run-ruby-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2 # Specify the Ruby version you want to use

    - name: Run Ruby script
      run: |
        ruby -v # Check Ruby version
        ruby script.rb # Replace 'script.rb' with your Ruby script
